# Generated by Django 6.0.5 on 2026-05-13 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageEnCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Start Date')),
                ('date_fin_prevue', models.DateField(verbose_name='Expected End Date')),
                ('date_fin_reelle', models.DateField(blank=True, null=True, verbose_name='Actual End Date')),
                ('sujet_stage', models.CharField(max_length=300, verbose_name='Internship Topic')),
                ('objectifs', models.TextField(verbose_name='Objectives')),
                ('convention_stage', models.FileField(blank=True, null=True, upload_to='stages/conventions/', verbose_name='Internship Agreement (PDF)')),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planned'), ('EN_COURS', 'In Progress'), ('SUSPENDU', 'Suspended'), ('TERMINE', 'Completed')], default='PLANIFIE', max_length=20, verbose_name='Status')),
                ('rapport_final', models.FileField(blank=True, null=True, upload_to='stages/rapports/', verbose_name='Final Report (PDF)')),
                ('soutenance_date', models.DateTimeField(blank=True, null=True, verbose_name='Defense Date')),
                ('soutenance_lieu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Defense Location')),
                ('note_finale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Final Grade')),
                ('mention', models.CharField(blank=True, max_length=50, null=True, verbose_name='Honors')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('enseignant_encadrant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages_encadres', to='accounts.enseignant', verbose_name='Supervising Teacher')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages_accueillis', to='accounts.entreprise', verbose_name='Company')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='accounts.etudiant', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Ongoing Internship',
                'verbose_name_plural': 'Ongoing Internships',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='MessageInterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200, verbose_name='Subject')),
                ('contenu', models.TextField(verbose_name='Content')),
                ('lu', models.BooleanField(default=False, verbose_name='Read')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name='Sent Date')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='stages.stageencours', verbose_name='Related Internship')),
            ],
            options={
                'verbose_name': 'Internal Message',
                'verbose_name_plural': 'Internal Messages',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='VisiteTerrainRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rapport', models.DateField(verbose_name='Report Date')),
                ('semaine_numero', models.IntegerField(verbose_name='Week Number')),
                ('avancement', models.IntegerField(default=0, verbose_name='Progress (%)')),
                ('taches_realisees', models.TextField(verbose_name='Tasks Completed')),
                ('difficultes', models.TextField(blank=True, null=True, verbose_name='Difficulties Encountered')),
                ('prochaines_etapes', models.TextField(verbose_name='Next Steps')),
                ('commentaire_enseignant', models.TextField(blank=True, null=True, verbose_name='Teacher Comment')),
                ('valide_par_enseignant', models.BooleanField(default=False, verbose_name='Validated by Teacher')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Validation Date')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Submission Date')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_rediges', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='stages.stageencours', verbose_name='Internship')),
            ],
            options={
                'verbose_name': 'Field Visit Report',
                'verbose_name_plural': 'Field Visit Reports',
                'ordering': ['semaine_numero'],
            },
        ),
        migrations.AddIndex(
            model_name='stageencours',
            index=models.Index(fields=['statut', 'date_debut'], name='stages_stag_statut_cea3fe_idx'),
        ),
        migrations.AddIndex(
            model_name='stageencours',
            index=models.Index(fields=['etudiant', 'statut'], name='stages_stag_etudian_a2163e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='visiteterrainrapport',
            unique_together={('stage', 'semaine_numero')},
        ),
    ]
