# Generated by Django 6.0.5 on 2026-05-13 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Skill Name')),
                ('categorie', models.CharField(blank=True, max_length=50, null=True, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Major Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Major',
                'verbose_name_plural': 'Majors',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='OffreStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('missions', models.TextField(verbose_name='Missions and Responsibilities')),
                ('type_stage', models.CharField(choices=[('INITIATION', 'Initiation Internship'), ('PERFECTIONNEMENT', 'Advanced Internship'), ('PFA', 'End-of-Year Project (PFA)'), ('PFE', 'End-of-Studies Project (PFE)')], max_length=20, verbose_name='Internship Type')),
                ('duree_semaines', models.IntegerField(default=8, verbose_name='Duration (weeks)')),
                ('date_debut', models.DateField(verbose_name='Start Date')),
                ('date_fin_candidature', models.DateField(verbose_name='Application Deadline')),
                ('niveau_requis', models.CharField(choices=[('L1', 'License Year 1'), ('L2', 'License Year 2'), ('L3', 'License Year 3'), ('M1', 'Master Year 1'), ('M2', 'Master Year 2')], max_length=2, verbose_name='Required Level')),
                ('localisation', models.CharField(max_length=200, verbose_name='Location')),
                ('teletravail', models.BooleanField(default=False, verbose_name='Remote Work Available')),
                ('gratification_montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stipend Amount')),
                ('gratification_devise', models.CharField(default='EUR', max_length=3, verbose_name='Currency')),
                ('nombre_postes', models.IntegerField(default=1, verbose_name='Number of Positions')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Draft'), ('PUBLIEE', 'Published'), ('EXPIREE', 'Expired'), ('POURVUE', 'Filled')], default='BROUILLON', max_length=20, verbose_name='Status')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Publication Date')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Last Modified Date')),
                ('competences_requises', models.ManyToManyField(blank=True, related_name='offres', to='offres.competence', verbose_name='Required Skills')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='accounts.entreprise', verbose_name='Company')),
                ('filieres_ciblees', models.ManyToManyField(blank=True, related_name='offres', to='offres.filiere', verbose_name='Targeted Majors')),
            ],
            options={
                'verbose_name': 'Internship Offer',
                'verbose_name_plural': 'Internship Offers',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name='Added Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Personal Notes')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='accounts.etudiant', verbose_name='Student')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='offres.offrestage', verbose_name='Offer')),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.AddIndex(
            model_name='offrestage',
            index=models.Index(fields=['statut', 'date_publication'], name='offres_offr_statut_474d56_idx'),
        ),
        migrations.AddIndex(
            model_name='offrestage',
            index=models.Index(fields=['type_stage', 'niveau_requis'], name='offres_offr_type_st_300a57_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favori',
            unique_together={('etudiant', 'offre')},
        ),
    ]
