# Generated by Django 6.0.5 on 2026-05-13 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('INSCRIPTION_BIENVENUE', 'Welcome Email'), ('CANDIDATURE_RECUE', 'Application Received'), ('CANDIDATURE_STATUT_CHANGE', 'Application Status Changed'), ('RAPPEL_RAPPORT_HEBO', 'Weekly Report Reminder'), ('RAPPEL_SOUTENANCE_J7', 'Defense Reminder J-7'), ('RAPPEL_SOUTENANCE_J1', 'Defense Reminder J-1'), ('ATTRIBUTION_ENCADRANT', 'Supervisor Assignment'), ('VALIDATION_COMPTE', 'Account Validation')], max_length=50, unique=True, verbose_name='Template Name')),
                ('sujet', models.CharField(max_length=300, verbose_name='Email Subject')),
                ('contenu_html', models.TextField(help_text='HTML content of the email. Use {{ variable }} for dynamic content.', verbose_name='HTML Content')),
                ('contenu_texte', models.TextField(blank=True, help_text='Plain text version of the email.', null=True, verbose_name='Plain Text Content')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Active')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Last Modified Date')),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
            },
        ),
        migrations.CreateModel(
            name='LogEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire', models.EmailField(max_length=254, verbose_name='Recipient Email')),
                ('sujet', models.CharField(max_length=300, verbose_name='Subject')),
                ('statut', models.CharField(choices=[('ENVOYE', 'Sent'), ('ECHEC', 'Failed'), ('EN_ATTENTE', 'Pending')], default='EN_ATTENTE', max_length=20, verbose_name='Status')),
                ('erreur_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name='Sent Date')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notifications.emailtemplate', verbose_name='Template Used')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('type_notification', models.CharField(choices=[('INSCRIPTION', 'Account Registration'), ('CANDIDATURE_STATUT', 'Application Status Change'), ('NOUVELLE_CANDIDATURE', 'New Application Received'), ('RAPPORT_EN_ATTENTE', 'Report Pending Review'), ('RAPPEL_SOUTENANCE', 'Defense Reminder'), ('ATTRIBUTION_ENCADRANT', 'Supervisor Assignment'), ('MESSAGE_NOUVEAU', 'New Message'), ('OFFRE_EXPIREE', 'Offer Expired'), ('GENERAL', 'General Notification')], default='GENERAL', max_length=30, verbose_name='Notification Type')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('lien_url', models.URLField(blank=True, null=True, verbose_name='Related URL')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['destinataire', 'is_read'], name='notificatio_destina_f86ce4_idx'), models.Index(fields=['type_notification', 'date_creation'], name='notificatio_type_no_fe35aa_idx')],
            },
        ),
    ]
