# Generated by Django 6.0.5 on 2026-05-13 00:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ETUDIANT', 'Student'), ('ENTREPRISE', 'Company'), ('ENSEIGNANT', 'Teacher'), ('ADMIN', 'Administrator')], default='ETUDIANT', max_length=20, verbose_name='Role')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profiles/photos/', verbose_name='Profile Photo')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Account Created Date')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-date_creation'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(max_length=100, verbose_name='Department')),
                ('specialite', models.CharField(max_length=100, verbose_name='Specialization')),
                ('grade', models.CharField(max_length=50, verbose_name='Academic Rank')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=200, verbose_name='Company Name')),
                ('secteur_activite', models.CharField(max_length=100, verbose_name='Industry Sector')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Company Description')),
                ('site_web', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/', verbose_name='Company Logo')),
                ('adresse', models.TextField(verbose_name='Address')),
                ('ville', models.CharField(max_length=100, verbose_name='City')),
                ('nombre_employes', models.IntegerField(blank=True, null=True, verbose_name='Number of Employees')),
                ('siret', models.CharField(max_length=20, verbose_name='SIRET/Tax ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entreprise_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['nom_entreprise'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.CharField(max_length=100, verbose_name='Major/Field of Study')),
                ('niveau', models.CharField(choices=[('L1', 'License Year 1'), ('L2', 'License Year 2'), ('L3', 'License Year 3'), ('M1', 'Master Year 1'), ('M2', 'Master Year 2')], max_length=2, verbose_name='Academic Level')),
                ('numero_etudiant', models.CharField(max_length=20, unique=True, verbose_name='Student ID Number')),
                ('cv', models.FileField(blank=True, null=True, upload_to='students/cv/', verbose_name='CV (PDF)')),
                ('lettre_motivation', models.TextField(blank=True, null=True, verbose_name='Cover Letter')),
                ('annee_academique', models.CharField(default='2024-2025', max_length=9, verbose_name='Academic Year')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['numero_etudiant'],
            },
        ),
    ]
