# Generated by Django 6.0.5 on 2026-05-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='cv_binary',
            field=models.BinaryField(blank=True, null=True, verbose_name='CV Content (Binary)'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='cv_filename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CV Filename'),
        ),
    ]
