# Generated by Django 6.0.5 on 2026-05-13 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encadrant_industriel_nom', models.CharField(blank=True, max_length=200, null=True, verbose_name='Industry Supervisor Name')),
                ('encadrant_industriel_entreprise', models.CharField(blank=True, max_length=200, null=True, verbose_name='Industry Supervisor Company')),
                ('titre_pfa', models.CharField(max_length=300, verbose_name='Project Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('domaine', models.CharField(max_length=100, verbose_name='Domain')),
                ('mots_cles', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=300, null=True, verbose_name='Keywords')),
                ('annee_academique', models.CharField(default='2024-2025', max_length=9, verbose_name='Academic Year')),
                ('semestre', models.CharField(choices=[('S1', 'Semester 1'), ('S2', 'Semester 2'), ('S3', 'Semester 3'), ('S4', 'Semester 4')], default='S2', max_length=20, verbose_name='Semester')),
                ('statut', models.CharField(choices=[('PROPOSE', 'Proposed'), ('VALIDE', 'Validated'), ('EN_COURS', 'In Progress'), ('SOUTENU', 'Defended'), ('ARCHIVE', 'Archived')], default='PROPOSE', max_length=20, verbose_name='Status')),
                ('note_encadrant', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Supervisor Grade')),
                ('note_jury', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Jury Grade')),
                ('note_finale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Final Grade')),
                ('rapport_pfa', models.FileField(blank=True, null=True, upload_to='pfa/rapports/', verbose_name='Project Report (PDF)')),
                ('code_source_url', models.URLField(blank=True, null=True, verbose_name='Source Code URL (GitHub)')),
                ('date_soutenance', models.DateTimeField(blank=True, null=True, verbose_name='Defense Date')),
                ('lieu_soutenance', models.CharField(blank=True, max_length=200, null=True, verbose_name='Defense Location')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Last Modified Date')),
                ('encadrant_academique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pfa_encadres', to='accounts.enseignant', verbose_name='Academic Supervisor')),
                ('etudiants', models.ManyToManyField(related_name='pfa', to='accounts.etudiant', verbose_name='Students')),
                ('membres_jury', models.ManyToManyField(blank=True, related_name='pfa_jury', to='accounts.enseignant', verbose_name='Jury Members')),
            ],
            options={
                'verbose_name': 'End-of-Year Project (PFA)',
                'verbose_name_plural': 'End-of-Year Projects (PFA)',
                'ordering': ['-annee_academique', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='EtapePFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_etape', models.CharField(max_length=200, verbose_name='Step Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_debut_prevue', models.DateField(verbose_name='Planned Start Date')),
                ('date_fin_prevue', models.DateField(verbose_name='Planned End Date')),
                ('date_fin_reelle', models.DateField(blank=True, null=True, verbose_name='Actual End Date')),
                ('priorite', models.CharField(choices=[('HAUTE', 'High'), ('MOYENNE', 'Medium'), ('BASSE', 'Low')], default='MOYENNE', max_length=10, verbose_name='Priority')),
                ('statut', models.CharField(choices=[('A_FAIRE', 'To Do'), ('EN_COURS', 'In Progress'), ('TERMINE', 'Completed'), ('BLOQUE', 'Blocked')], default='A_FAIRE', max_length=20, verbose_name='Status')),
                ('responsable', models.CharField(blank=True, max_length=200, null=True, verbose_name='Person Responsible')),
                ('commentaires', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('ordre', models.IntegerField(default=0, verbose_name='Order')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('pfa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='pfa.pfa', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Step',
                'verbose_name_plural': 'Project Steps',
                'ordering': ['ordre', 'date_debut_prevue'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Document Title')),
                ('fichier', models.FileField(upload_to='pfa/documents/', verbose_name='File')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Version')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_pfa_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
                ('pfa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pfa.pfa', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'PFA Document',
                'verbose_name_plural': 'PFA Documents',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='ReunionSuivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reunion', models.DateTimeField(verbose_name='Meeting Date')),
                ('participants', models.TextField(help_text='Comma-separated list of participants', verbose_name='Participants')),
                ('compte_rendu', models.TextField(verbose_name='Meeting Minutes')),
                ('prochaine_echeance', models.DateField(blank=True, null=True, verbose_name='Next Deadline')),
                ('actions_a_mener', models.TextField(blank=True, null=True, verbose_name='Action Items')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('pfa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunions', to='pfa.pfa', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Follow-up Meeting',
                'verbose_name_plural': 'Follow-up Meetings',
                'ordering': ['-date_reunion'],
            },
        ),
        migrations.AddIndex(
            model_name='pfa',
            index=models.Index(fields=['statut', 'annee_academique'], name='pfa_pfa_statut_eba3eb_idx'),
        ),
        migrations.AddIndex(
            model_name='pfa',
            index=models.Index(fields=['domaine', 'statut'], name='pfa_pfa_domaine_7f31ee_idx'),
        ),
        migrations.AddIndex(
            model_name='etapepfa',
            index=models.Index(fields=['statut', 'priorite'], name='pfa_etapepf_statut_d2b7e4_idx'),
        ),
    ]
