# Generated by Django 6.0.5 on 2026-05-13 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagePFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Content')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name='Sent Date')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_pfa', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('pfa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pfa.pfa', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'PFA Message',
                'verbose_name_plural': 'PFA Messages',
                'ordering': ['date_envoi'],
            },
        ),
    ]
