# Generated by Django 6.0.5 on 2026-05-13 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('offres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeStageLibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine_recherche', models.CharField(max_length=200, verbose_name='Desired Field')),
                ('periode_souhaitee', models.CharField(max_length=100, verbose_name='Desired Period')),
                ('type_stage', models.CharField(choices=[('INITIATION', 'Initiation Internship'), ('PERFECTIONNEMENT', 'Advanced Internship'), ('PFA', 'End-of-Year Project (PFA)'), ('PFE', 'End-of-Studies Project (PFE)')], max_length=20, verbose_name='Internship Type')),
                ('lettre', models.TextField(verbose_name='Cover Letter')),
                ('cv', models.FileField(upload_to='demandes_libres/cv/', verbose_name='CV')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'Pending'), ('VALIDEE', 'Validated'), ('ARCHIVEE', 'Archived')], default='EN_ATTENTE', max_length=20, verbose_name='Status')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Submission Date')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Validation Date')),
                ('enseignant_referent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_suivies', to='accounts.enseignant', verbose_name='Supervising Teacher')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_libres', to='accounts.etudiant', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Free Internship Request',
                'verbose_name_plural': 'Free Internship Requests',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lettre_motivation', models.TextField(blank=True, null=True, verbose_name='Cover Letter')),
                ('cv_version', models.FileField(blank=True, null=True, upload_to='candidatures/cv/', verbose_name='CV Version (snapshot)')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'Pending'), ('VUE', 'Viewed'), ('RETENUE', 'Shortlisted'), ('REFUSEE', 'Rejected'), ('ACCEPTEE', 'Accepted')], default='EN_ATTENTE', max_length=20, verbose_name='Status')),
                ('date_candidature', models.DateTimeField(auto_now_add=True, verbose_name='Application Date')),
                ('date_derniere_maj', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('message_entreprise', models.TextField(blank=True, null=True, verbose_name='Company Message/Feedback')),
                ('note_interne_enseignant', models.TextField(blank=True, null=True, verbose_name='Internal Teacher Note')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='accounts.etudiant', verbose_name='Student')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='offres.offrestage', verbose_name='Offer')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-date_candidature'],
                'indexes': [models.Index(fields=['statut', 'date_candidature'], name='candidature_statut_57505b_idx'), models.Index(fields=['etudiant', 'statut'], name='candidature_etudian_86229a_idx')],
                'unique_together': {('etudiant', 'offre')},
            },
        ),
    ]
